changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Security Changes
      labels:
        - security
    - title: 🛠 Breaking Changes
      labels:
        - breaking-change
      exclude:
        labels:
          - security
    - title: 🏕 Features
      labels:
        - enhancement
        - feature
      exclude:
        labels:
          - security
    - title: 👒 Dependencies
      labels:
        - dependencies
      exclude:
        labels:
          - security
          - breaking-change
          - enhancement
          - feature
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - breaking-change
          - enhancement
          - feature
          - dependencies
          - security